<a href="https://colab.research.google.com/github/Suryaprakash17/Small-project/blob/main/Smallproj2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Numpy array**

In [ ]:
import numpy
import numpy as np

In [ ]:
ar=np.arange(2,51,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


**2. List from user**

In [19]:
import numpy as np
lst1=[]
lst2=[]
ar=int(input("Enter the 1st elements: "))
for i in range (0,ar):
  lst1.append(i)
print(lst1)
ar1=int(input("Enter the 1st elements: "))
for i in range (0,ar1):
  lst2.append(i)
print(lst2)
np1=np.array(lst1)
np2=np.array(lst2)
print("Array list1:",np1)
print("Array list25:",np2)
con=np.concatenate((np1,np2))
print('Concatenate=',con)
print('Sort=',np.sort(con))

Enter the 1st elements: 4
[0, 1, 2, 3]
Enter the 1st elements: 5
[0, 1, 2, 3, 4]
Array list1: [0 1 2 3]
Array list25: [0 1 2 3 4]
Concatenate= [0 1 2 3 0 1 2 3 4]
Sort= [0 0 1 1 2 2 3 3 4]


**3. Dimentions**

In [39]:
a=np.arange(15).reshape(3,5)
print(a)
print("Dimension=",a.ndim)
print("Size=",a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Dimension= 2
Size= 15


**4. Convert 1D to 2D**

In [124]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
arr=arr[np.newaxis,...,np.newaxis,np.newaxis]
print(arr.shape)


[1 2 3 4 5]
1
(1, 5, 1, 1)


In [111]:
d=np.array([0,1,2,3,4,5])
print(d.shape)
d1=np.expand_dims(d,axis=0)
print(d1.shape)

(6,)
(1, 6)


**5. Horizontal and vertical**

In [132]:
arr=np.array([1,2,3,4])
print(arr)
arr1=np.array([5,6,7,8])
print(arr1)
ver=np.vstack((arr,arr1))
hor=np.hstack((arr,arr1))
print()
print("Vertical Stack=",ver)
print("Horizontal Stack=",hor)

[1 2 3 4]
[5 6 7 8]

Vertical Stack= [[1 2 3 4]
 [5 6 7 8]]
Horizontal Stack= [1 2 3 4 5 6 7 8]


**6. Unique items and counts unique items**

In [140]:
import numpy as np

a = np.array([1,2,2,2,2,3,4,4,4,4,5,5,100,100,6,6,6,7,7])
(unique , count) = np.unique(a,return_counts=True)

print(unique,count)

[  1   2   3   4   5   6   7 100] [1 4 1 4 2 3 2 2]
